In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/RohitChaudhary65/SC07-Smart-Irrigation-System/step-2-data-pipeline/data/sample_input.csv"

df = pd.read_csv(url)

df.head()

,sample_id,soil_moisture_pct,temperature_c,humidity_pct,rainfall_mm,soil_ph,irrigation_target
0,IRR-001,22,34,38,0,6.5,1
1,IRR-002,48,29,55,2,6.8,0
2,IRR-003,31,36,42,0,6.2,1
3,IRR-004,67,27,68,8,7.1,0
4,IRR-005,28,33,45,1,6.4,1

In [2]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nFirst 5 rows:")
display(df.head())

Shape: (20, 7)

Columns:
['sample_id', 'soil_moisture_pct', 'temperature_c', 'humidity_pct', 'rainfall_mm', 'soil_ph', 'irrigation_target']

Data types:
sample_id             object
soil_moisture_pct      int64
temperature_c          int64
humidity_pct           int64
rainfall_mm            int64
soil_ph              float64
irrigation_target      int64
dtype: object

Missing values:
sample_id            0
soil_moisture_pct    0
temperature_c        0
humidity_pct         0
rainfall_mm          0
soil_ph              0
irrigation_target    0
dtype: int64

Duplicate rows: 0

First 5 rows:

,sample_id,soil_moisture_pct,temperature_c,humidity_pct,rainfall_mm,soil_ph,irrigation_target
0,IRR-001,22,34,38,0,6.5,1
1,IRR-002,48,29,55,2,6.8,0
2,IRR-003,31,36,42,0,6.2,1
3,IRR-004,67,27,68,8,7.1,0
4,IRR-005,28,33,45,1,6.4,1

In [3]:
print("Irrigation Target Distribution:")
print(df["irrigation_target"].value_counts())

Irrigation Target Distribution:
irrigation_target
1    10
0    10
Name: count, dtype: int64